# JSON from the raw cuadrante data at the SSPDF find your cop thingy
JSON = js/cuads.json js/msg.json js/names.json
# Files generated by run-all.R 
R = graphs/total-sector-hom.png graphs/total-sector-rncv.png \
    graphs/total-sector-rvcv.png data/interactive-cuadrantes.csv \
    data/interactive-sectores.csv data/topo-cuadrantes.csv \
    data/topo-sectores.csv html/js/hom-dol-sector.js \
    html/js/hom-dol-cuad.js clean-data/df-crime.csv
# Html from the mustache templates
HTML = html/cuadrantes.html html/sectores.html
.PHONY: all clean

all: $(JSON) cuadrante-shps/cuadrantes-sspdf.shp html/js/cuadrantes.json \
     html/js/sectores.json html/js/sectores-map.json \
     html/js/cuadrantes-map.json html/js/cuadrantes-diff.json $(R) \
     node_modules/.bin/hulk html/counts.html html/index.html $(HTML)

clean:
	rm -rf $(JSON) html/js/sectores.json html/js/cuadrantes.json cuadrante-shps/cuadrantes-sspdf.shp $(R) $(HTML)



## Download the polygon coordinates from the police website
$(JSON): input.in.intermediate
.INTERMEDIATE: input.in.intermediate
input.in.intermediate: js/scrape_coordinates.js
	node $^

## Create a shapefile from the polygon coordinates we downloaded
cuadrante-shps/cuadrantes-sspdf.shp: create-sspdf-shp.R $(JSON)
	mkdir -p html/js
	Rscript --no-save --no-restore --verbose create-sspdf-shp.R
	touch $@

## Create a projected topojson useful for the leaflet map
html/js/cuadrantes-map.json: cuadrante-shps/cuadrantes-sspdf-no-errors2.shp
	topojson --id-property=id \
	--external-properties data/interactive-cuadrantes.csv \
	-s 1e-10 \
	-o $@ \
	--properties id,sector,population,id,hom_rate,rncv_rate,rvcv_rate,rvsv_rate,viol_rate,hom_count,rncv_count,rvcv_count,rvsv_count,viol_count \
	-- cuadrantes=$^

## Unprojected topojson of the police cuadrantes
html/js/cuadrantes.json: cuadrante-shps/cuadrantes-sspdf-no-errors2.shp
#topojson --id-property=id -s 1e-9  -o $@ --properties sector,id -- cuadrantes=$^
	topojson \
	--width 960 \
	--height 800 \
	--margin 0 \
	--external-properties data/topo-cuadrantes.csv \
	--id-property=id  \
        -s 1e-10 \
	--projection 'd3.geo.mercator()' \
	-o $@ \
	--properties sector,id,hom,rncv,rvcv,rvsv,viol \
	cuadrantes=$^

## Unprojected topojson of the police cuadrantes for the difference map
html/js/cuadrantes-diff.json: cuadrante-shps/cuadrantes-sspdf-no-errors2.shp
#topojson --id-property=id -s 1e-9  -o $@ --properties sector,id -- cuadrantes=$^
	topojson \
	--width 960 \
	--height 800 \
	--margin 0 \
	--external-properties data/topo-cuadrantes-diff.csv \
	--id-property=id  \
	-s 1e-10 \
	--projection 'd3.geo.mercator()' \
	-o $@ \
	--properties sector,id,hom,rncv,rvcv,rvsv,viol \
	cuadrantes=$^

## Projected Sectores topojson for the leaflet map
html/js/sectores-map.json: cuadrante-shps/sectores.shp
	topojson --id-property=sector \
        --external-properties data/interactive-sectores.csv \
	-s 1e-10 \
        -o $@ \
        --properties sector,population,id,hom_rate,rncv_rate,rvcv_rate,rvsv_rate,viol_rate,hom_count,rncv_count,rvcv_count,rvsv_count,viol_count \
        -- sectores=$^	

## Unprojected topojson of the police sectors (made up of many cuadrantes)
html/js/sectores.json: cuadrante-shps/sectores.shp
	topojson \
	--width 960 \
	--height 800 \
	--margin 0 \
	--external-properties data/topo-sectores.csv \
	--id-property=sector  \
	-s .9 \
	--projection 'd3.geo.mercator()' \
	-o $@ \
	--properties sector,id,hom,rncv,rvcv,rvsv,viol \
	sectores=$^

html/counts.html: interactive-maps/counts.html
	sed --e '/\<tablehom\>/{r interactive-maps/table-hom-cuadrantes.html' -e 'd}' --e '/\<tablerncv\>/{r interactive-maps/table-rncv-cuadrantes.html' -e 'd}' --e '/\<tablervcv\>/{r interactive-maps/table-rvcv-cuadrantes.html' -e 'd}' --e '/\<tablervsv\>/{r interactive-maps/table-rvsv-cuadrantes.html' -e 'd}' --e '/\<tableviol\>/{r interactive-maps/table-viol-cuadrantes.html' -e 'd}' --e '/\<vecCuadrantes\>/{r interactive-maps/vecCuadrantes.txt' -e 'd}'  interactive-maps/counts.html > html/counts.html

html/index.html: interactive-maps/index.html
	sed --e '/\<tablehom\>/{r interactive-maps/table-hom-sectores.html' -e 'd}' --e '/\<tablerncv\>/{r interactive-maps/table-rncv-sectores.html' -e 'd}' --e '/\<tablervcv\>/{r interactive-maps/table-rvcv-sectores.html' -e 'd}' --e '/\<tablervsv\>/{r interactive-maps/table-rvsv-sectores.html' -e 'd}' --e '/\<tableviol\>/{r interactive-maps/table-viol-sectores.html' -e 'd}' --e '/\<vecSector\>/{r interactive-maps/vecSector.txt' -e 'd}' interactive-maps/index.html > html/index.html


$(R): input.in.intermediate2
.INTERMEDIATE: input.in.intermediate2
input.in.intermediate2: run-all.R
	Rscript --no-save --no-restore --verbose $^

## install the hogan mustache template engine
node_modules/.bin/hulk:
	npm install hogan.js

## Create sector and cuadrante leaflet map from a template
$(HTML): input.in.intermediate3
.INTERMEDIATE: input.in.intermediate3
input.in.intermediate3: node_modules/.bin/hulk interactive-maps/index.js interactive-maps/leaflet.mustache
	node interactive-maps/index.js
